apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker
metadata:
  name: earth-moon
spec:
  replicas: 1
  consumer:
    bootstrapServers: 'earth-cluster-kafka-bootstrap.kafka-demo-earth.svc:9092'
    groupId: mirror-maker-user1
    config:
      auto.offset.reset: earliest
  producer:
    bootstrapServers: 'moon-kafka-bootstrap.kafka-demo-moon.svc:9092'
  whitelist: user1.earth.*